import Head from 'next/head';
import Image from 'next/image';
import styled from "styled-components";

export default function Home() {
  return (
    <>
      {/* <Head>
        <title>아이겟</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head> */}
      <h1>안녕</h1>
    </>
  )
}
